/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AudioController: typeof import('./../components/Controller/AudioController.vue')['default']
    Button: typeof import('./../components/ui/button/Button.vue')['default']
    ContextMenu: typeof import('./../components/ui/context-menu/ContextMenu.vue')['default']
    ContextMenuCheckboxItem: typeof import('./../components/ui/context-menu/ContextMenuCheckboxItem.vue')['default']
    ContextMenuContent: typeof import('./../components/ui/context-menu/ContextMenuContent.vue')['default']
    ContextMenuGroup: typeof import('./../components/ui/context-menu/ContextMenuGroup.vue')['default']
    ContextMenuItem: typeof import('./../components/ui/context-menu/ContextMenuItem.vue')['default']
    ContextMenuLabel: typeof import('./../components/ui/context-menu/ContextMenuLabel.vue')['default']
    ContextMenuPortal: typeof import('./../components/ui/context-menu/ContextMenuPortal.vue')['default']
    ContextMenuRadioGroup: typeof import('./../components/ui/context-menu/ContextMenuRadioGroup.vue')['default']
    ContextMenuRadioItem: typeof import('./../components/ui/context-menu/ContextMenuRadioItem.vue')['default']
    ContextMenuSeparator: typeof import('./../components/ui/context-menu/ContextMenuSeparator.vue')['default']
    ContextMenuShortcut: typeof import('./../components/ui/context-menu/ContextMenuShortcut.vue')['default']
    ContextMenuSub: typeof import('./../components/ui/context-menu/ContextMenuSub.vue')['default']
    ContextMenuSubContent: typeof import('./../components/ui/context-menu/ContextMenuSubContent.vue')['default']
    ContextMenuSubTrigger: typeof import('./../components/ui/context-menu/ContextMenuSubTrigger.vue')['default']
    ContextMenuTrigger: typeof import('./../components/ui/context-menu/ContextMenuTrigger.vue')['default']
    CreateListDialog: typeof import('./../components/CreateListDialog.vue')['default']
    Dialog: typeof import('./../components/ui/dialog/Dialog.vue')['default']
    DialogClose: typeof import('./../components/ui/dialog/DialogClose.vue')['default']
    DialogContent: typeof import('./../components/ui/dialog/DialogContent.vue')['default']
    DialogDescription: typeof import('./../components/ui/dialog/DialogDescription.vue')['default']
    DialogFooter: typeof import('./../components/ui/dialog/DialogFooter.vue')['default']
    DialogHeader: typeof import('./../components/ui/dialog/DialogHeader.vue')['default']
    DialogScrollContent: typeof import('./../components/ui/dialog/DialogScrollContent.vue')['default']
    DialogTitle: typeof import('./../components/ui/dialog/DialogTitle.vue')['default']
    DialogTrigger: typeof import('./../components/ui/dialog/DialogTrigger.vue')['default']
    Footer: typeof import('./../components/Layout/Footer/index.vue')['default']
    Header: typeof import('./../components/MusicList/Header/index.vue')['default']
    ImportMusic: typeof import('./../components/MusicList/Header/ImportMusic.vue')['default']
    Input: typeof import('./../components/ui/input/Input.vue')['default']
    Item: typeof import('./../components/MusicList/List/Item.vue')['default']
    Layout: typeof import('./../components/Layout/index.vue')['default']
    List: typeof import('./../components/MusicList/List/index.vue')['default']
    Main: typeof import('./../components/Layout/Main/index.vue')['default']
    MusicList: typeof import('./../components/MusicList/index.vue')['default']
    PlaylistMenu: typeof import('./../components/MusicList/List/PlaylistMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./../components/Layout/Sidebar/index.vue')['default']
    Slider: typeof import('./../components/ui/slider/Slider.vue')['default']
    Textarea: typeof import('./../components/ui/textarea/Textarea.vue')['default']
    Toggle: typeof import('./../components/ui/toggle/Toggle.vue')['default']
    ToggleGroup: typeof import('./../components/ui/toggle-group/ToggleGroup.vue')['default']
    ToggleGroupItem: typeof import('./../components/ui/toggle-group/ToggleGroupItem.vue')['default']
    UploadImage: typeof import('./../components/UploadImage.vue')['default']
    VolumeControl: typeof import('./../components/Controller/VolumeControl.vue')['default']
  }
}
